### PR TITLE
updated hapi version, removed STU3 & R4B versions. These are to move …

### PR DESCRIPTION
**Pull request by ryma2fhir**
updated hapi version, removed STU3 & R4B versions. These are to move to a seperate branch away from main.

not to be pushed until ran as local instance and UK Core validated against it.

### CODE REVIEW

**Comment by declankieran-nhsd** [comment]
@ryma2fhir How are you building this?  I'm using maven and pretty sure the build is broken.

**Comment by declankieran-nhsd** [comment]
@ryma2fhir If you add a prefix of WIP: to the PR title, that will stop it from being mergeable until its ready to be reviewed

**Comment by ryma2fhir** [comment]
Cheers, I've moved it into draft. I originally had it running on a fork, but when I manually moved the changes here I must have missed a commit. Should have just done a PR from my fork.

**Comment by KevinMayfield** [comment]
Why do we need to remove STU3?
It has some features I use quite often such as converting from STU3 to R4.
No need for R4b though.

I'd suggest turning this into config rather than multiple branches, it will maintenance harder for limited benefit

**Comment by KevinMayfield** [comment]
Have redone this in https://github.com/NHSDigital/IOPS-FHIR-Validation-Service/blob/PDS-OAS-plus-HAPI-6-10/src/main/resources/application.yaml#L22

It's now configuration to disable.

**Pull request closed without merging**
